"""Training policies and loss calculations for Prism models."""

from prism.training.batches import (
    SupervisedTokenTaskBatch,
    build_supervised_sentence_batches,
    build_supervised_token_task_batch,
    iter_supervised_token_task_batches,
)
from prism.training.class_weights import (
    build_token_task_loss_weights,
)
from prism.training.morphology_bundle_reranking import (
    build_morphology_bundle_reranker_spec,
    deserialize_morphology_bundle_reranker_spec,
    serialize_morphology_bundle_reranker_spec,
)
from prism.training.checkpoints import (
    TOKEN_TASK_CHECKPOINT_FORMAT_VERSION,
    backbone_layer_aggregation_strategy_from_checkpoint,
    token_pooling_strategy_from_checkpoint,
    token_task_head_architecture_from_checkpoint,
    validate_token_task_checkpoint_format,
    character_vocabulary_from_checkpoint,
    maximum_character_count_from_checkpoint,
    morphology_logit_correction_from_checkpoint,
    morphology_pre_head_architecture_from_checkpoint,
    morphology_weights_from_checkpoint,
    morphology_bundle_reranker_spec_from_checkpoint,
)
from prism.training.calibration import (
    TASK_TEMPERATURE_CALIBRATION_FORMAT_VERSION,
    CalibratedTaskProbabilities,
    CalibrationStatistics,
    HeadCalibrationReport,
    TaskTemperatureCalibration,
    calibrate_task_heads,
    calibrated_task_probabilities,
    load_task_temperature_calibration,
    write_task_temperature_calibration,
)
from prism.training.silver_labeling import (
    SILVER_LABEL_FORMAT_VERSION,
    SilverLabelManifest,
    SilverLabelShardReference,
    SilverSentenceLabels,
    generate_silver_labels,
    iter_silver_label_records,
    load_silver_label_manifest,
    write_silver_label_manifest,
    write_silver_label_shard,
)
from prism.training.config import (
    CheckpointSelectionMetric,
    SupervisedTrainingConfig,
)
from prism.training.distillation import (
    CombinedTokenTaskLosses,
    TokenTaskDistillationPolicy,
    calculate_binary_distillation_loss,
    calculate_categorical_distillation_loss,
    calculate_decoupled_categorical_distillation_loss,
    combine_token_task_losses,
    compute_token_task_distillation_loss,
)
from prism.training.epochs import (
    DistilledEpochMetrics,
    MixedEpochMetrics,
    SupervisedEpochMetrics,
    SupervisedEvaluationMetrics,
    evaluate_supervised_token_task_epoch,
    train_distilled_token_task_epoch,
    train_mixed_token_task_epoch,
    train_supervised_token_task_epoch,
)
from prism.training.relation_distillation import (
    RelationDistillationPolicy,
    compute_token_relation_loss,
)
from prism.training.silver_batches import (
    SilverFilterPolicy,
    SilverLoadReport,
    SilverTokenTaskBatch,
    SilverTrainingSentence,
    build_silver_sentence_batches,
    build_silver_token_task_batch,
    iter_silver_token_task_batches,
    load_silver_training_sentences,
)
from prism.training.silver_training import (
    SilverKdLosses,
    compute_silver_kd_loss,
    train_silver_kd_step,
)
from prism.training.losses import (
    MorphologyBundleLossPolicy,
    MorphologyBundleLossResult,
    TokenTaskLosses,
    TokenTaskLossWeights,
    calculate_morphology_bundle_loss,
    calculate_morphology_feature_loss,
    compute_token_task_loss,
)
from prism.training.optimizers import build_supervised_adamw_optimizer
from prism.training.runner import (
    SupervisedTrainingEpochResult,
    SupervisedTrainingRunResult,
    run_supervised_training_epochs,
)
from prism.training.schedulers import build_linear_warmup_decay_scheduler
from prism.training.steps import (
    evaluate_supervised_token_task_step,
    train_distilled_token_task_step,
    train_supervised_token_task_step,
)
from prism.training.task_interaction_audit import (
    GradientConflictAuditAccumulator,
    GradientConflictPairAudit,
    GradientParameterGroupAudit,
    LemmaRuleRankingAudit,
    MorphologyBundleRankingAudit,
    NamedRankAuditMetrics,
    RankAuditMetrics,
    TokenTaskInteractionAudit,
    TokenTaskRankAuditAccumulator,
    audit_token_task_interactions,
    evenly_spaced_batch_indices,
    token_task_shared_parameter_groups,
)

__all__ = [
    "TokenTaskLosses",
    "MorphologyBundleLossPolicy",
    "MorphologyBundleLossResult",
    "calculate_morphology_bundle_loss",
    "calculate_morphology_feature_loss",
    "compute_token_task_loss",
    "SupervisedTokenTaskBatch",
    "build_supervised_sentence_batches",
    "build_supervised_token_task_batch",
    "iter_supervised_token_task_batches",
    "evaluate_supervised_token_task_step",
    "train_supervised_token_task_step",
    "TASK_TEMPERATURE_CALIBRATION_FORMAT_VERSION",
    "CalibratedTaskProbabilities",
    "CalibrationStatistics",
    "HeadCalibrationReport",
    "TaskTemperatureCalibration",
    "calibrate_task_heads",
    "calibrated_task_probabilities",
    "load_task_temperature_calibration",
    "write_task_temperature_calibration",
    "SILVER_LABEL_FORMAT_VERSION",
    "SilverLabelManifest",
    "SilverLabelShardReference",
    "SilverSentenceLabels",
    "generate_silver_labels",
    "iter_silver_label_records",
    "load_silver_label_manifest",
    "write_silver_label_manifest",
    "write_silver_label_shard",
    "CheckpointSelectionMetric",
    "SupervisedTrainingConfig",
    "build_supervised_adamw_optimizer",
    "build_linear_warmup_decay_scheduler",
    "SupervisedEpochMetrics",
    "SupervisedEvaluationMetrics",
    "evaluate_supervised_token_task_epoch",
    "train_supervised_token_task_epoch",
    "train_distilled_token_task_step",
    "SupervisedTrainingEpochResult",
    "SupervisedTrainingRunResult",
    "run_supervised_training_epochs",
    "TokenTaskLossWeights",
    "build_token_task_loss_weights",
    "build_morphology_bundle_reranker_spec",
    "deserialize_morphology_bundle_reranker_spec",
    "serialize_morphology_bundle_reranker_spec",
    "calculate_binary_distillation_loss",
    "calculate_categorical_distillation_loss",
    "calculate_decoupled_categorical_distillation_loss",
    "compute_token_task_distillation_loss",
    "CombinedTokenTaskLosses",
    "TokenTaskDistillationPolicy",
    "combine_token_task_losses",
    "DistilledEpochMetrics",
    "MixedEpochMetrics",
    "train_distilled_token_task_epoch",
    "train_mixed_token_task_epoch",
    "RelationDistillationPolicy",
    "compute_token_relation_loss",
    "SilverFilterPolicy",
    "SilverLoadReport",
    "SilverTokenTaskBatch",
    "SilverTrainingSentence",
    "build_silver_sentence_batches",
    "build_silver_token_task_batch",
    "iter_silver_token_task_batches",
    "load_silver_training_sentences",
    "SilverKdLosses",
    "compute_silver_kd_loss",
    "train_silver_kd_step",
    "TOKEN_TASK_CHECKPOINT_FORMAT_VERSION",
    "backbone_layer_aggregation_strategy_from_checkpoint",
    "token_pooling_strategy_from_checkpoint",
    "token_task_head_architecture_from_checkpoint",
    "validate_token_task_checkpoint_format",
    "character_vocabulary_from_checkpoint",
    "maximum_character_count_from_checkpoint",
    "morphology_logit_correction_from_checkpoint",
    "morphology_pre_head_architecture_from_checkpoint",
    "morphology_weights_from_checkpoint",
    "morphology_bundle_reranker_spec_from_checkpoint",
    "GradientConflictPairAudit",
    "GradientConflictAuditAccumulator",
    "GradientParameterGroupAudit",
    "LemmaRuleRankingAudit",
    "MorphologyBundleRankingAudit",
    "NamedRankAuditMetrics",
    "RankAuditMetrics",
    "TokenTaskInteractionAudit",
    "TokenTaskRankAuditAccumulator",
    "audit_token_task_interactions",
    "evenly_spaced_batch_indices",
    "token_task_shared_parameter_groups",
]
